
address: :8089
prefix: /kk-aqueue/

db:
  title: 写数据库
  name: mysql
  url: root:123456@tcp(127.0.0.1:3306)/kk?charset=utf8mb4
  prefix: aqueue_
  maxIdleConns: 1
  maxOpenConns: 6

dbr:
  title: 读数据库
  name: mysql
  url: root:123456@tcp(127.0.0.1:3306)/kk?charset=utf8mb4
  prefix: aqueue_
  maxIdleConns: 6
  maxOpenConns: 20
